// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zGP93SgLx3vz-i0W4iTFBTa4SjbfPaI',
    appId: '1:791805299635:web:7978740baa12326efc59c6',
    messagingSenderId: '791805299635',
    projectId: 'flutter-task-b7e36',
    authDomain: 'flutter-task-b7e36.firebaseapp.com',
    storageBucket: 'flutter-task-b7e36.firebasestorage.app',
    measurementId: 'G-9EWZ9CZGX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD844xvJMMha8F8kJ-IERjjaXOlVzZ9U74',
    appId: '1:791805299635:android:37cdee586e1a1fe6fc59c6',
    messagingSenderId: '791805299635',
    projectId: 'flutter-task-b7e36',
    storageBucket: 'flutter-task-b7e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iLcac3Ctqkkt2zAkfr7frFsgDfrzeDE',
    appId: '1:791805299635:ios:05510031a4e697b5fc59c6',
    messagingSenderId: '791805299635',
    projectId: 'flutter-task-b7e36',
    storageBucket: 'flutter-task-b7e36.firebasestorage.app',
    iosClientId: '791805299635-e8sq80j3efjknqq2l2u9i97fm37t0lou.apps.googleusercontent.com',
    iosBundleId: 'com.example.figmaPracticeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9iLcac3Ctqkkt2zAkfr7frFsgDfrzeDE',
    appId: '1:791805299635:ios:05510031a4e697b5fc59c6',
    messagingSenderId: '791805299635',
    projectId: 'flutter-task-b7e36',
    storageBucket: 'flutter-task-b7e36.firebasestorage.app',
    iosClientId: '791805299635-e8sq80j3efjknqq2l2u9i97fm37t0lou.apps.googleusercontent.com',
    iosBundleId: 'com.example.figmaPracticeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zGP93SgLx3vz-i0W4iTFBTa4SjbfPaI',
    appId: '1:791805299635:web:260966eba8e79304fc59c6',
    messagingSenderId: '791805299635',
    projectId: 'flutter-task-b7e36',
    authDomain: 'flutter-task-b7e36.firebaseapp.com',
    storageBucket: 'flutter-task-b7e36.firebasestorage.app',
    measurementId: 'G-F8GV39V4B0',
  );
}
